#APPLICATION
spring.application.name=${APP_NAME:cloudstore-user-service}
server.port=${PORT:5000}

#DB
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/test_db}
spring.datasource.username=${DB_USERNAME:test_user}
spring.datasource.password=${DB_PASSWORD:test123}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}

#PRODUCT SERVICE
fakestore-url=http://fakestore-service-env.eba-nxxj3k3q.eu-north-1.elasticbeanstalk.com
#fakestore-url=${PRODUCT_SERVICE_URL:http://localhost:5001}


#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

#SERVER
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=${SHUTDOWN_TIMEOUT:30s}

#LOGS
logging.level.root=${LOG_LEVEL:INFO}





