spring.application.name=cloudstore-user-service
spring.datasource.url=jdbc:mysql://localhost:3306/test_db
spring.datasource.username=test_user
spring.datasource.password=test123

spring.jpa.hibernate.ddl-auto=update
spring.datasoructure.show-sql=true

# fakestore-base-url=http://fakestoreservice-env.eba-dnzki35b.eu-north-1.elasticbeanstalk.com/products

jwt.secret=XwJFdmA8O+qdKiegzd6nHAwpgM8MQezFoDyvunE0eB2Lx7PR519+8ZcyfcFSGHWJrHFFoxX9foIMyP/Dixeeqw==
jwt.expiration-ms=86400000

